export const allBtns = [
  { id: "7", content: "7" },
  { id: "8", content: "8" },
  { id: "9", content: "9" },
  { id: "back", content: "DEL" },
  { id: "4", content: "4" },
  { id: "5", content: "5" },
  { id: "6", content: "6" },
  { id: "plus", content: "+" },
  { id: "1", content: "1" },
  { id: "2", content: "2" },
  { id: "3", content: "3" },
  { id: "minus", content: "-" },
  { id: "dot", content: "." },
  { id: "0", content: "0" },
  { id: "div", content: "/" },
  { id: "mul", content: "*" },
  { id: "clr", content: "RESET", span: 2 },
  { id: "equal", content: "=", span: 2 },
];
